apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: match
spec:
  replicas: 2
  selector:
    app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
      - name: match
        image: pavlov/match:latest
        ports:
        - containerPort: 80
        env:
        - name: WORKER_COUNT
          valueFrom:
            secretKeyRef:
              name: match
              key: WORKER_COUNT
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: match
              key: ELASTICSEARCH_URL
        - name: ELASTICSEARCH_INDEX
          valueFrom:
            secretKeyRef:
              name: match
              key: ELASTICSEARCH_INDEX
        - name: ELASTICSEARCH_DOC_TYPE
          valueFrom:
            secretKeyRef:
              name: match
              key: ELASTICSEARCH_DOC_TYPE
